# Generated by Django 3.2.9 on 2021-12-14 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20211212_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='deadline',
            field=models.DateTimeField(verbose_name='срок устранения (до)'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_task', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CHECKED', 'Checked')], default='OPEN', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='задача'),
        ),
    ]
